docs: ADR-0006 sbom merge
bomctl/bomctl pull request #111
Opened 2024-07-29 19:31 UTC by pkwiatkowski1

# 6. Merge subcommand

Date: 2024-07-29

## Status

Accepted

## Context

SBOM merge capability should be supported.

## Decision

- Ability to take one or more SBOMs in different formats into a singular sbom
  - Merge components that may match on different identifiers (purls, hash, etc …)
    - Merge component dependencies
    - Merge component properties

- Ability to take a flag to “flatten” any externally referenced SBOMs
  - Any nested components should be moved to "top level" components and the depends_on section updated to show the dependency.

## Consequences

These changes allow end users to easily consolidate multiple SBOMs from a variety of different sources into one while still being agnostic of the SBOM format being used.

2024-07-29 19:38 UTC, jhoward-lm requested changes

2024-07-29 19:38 UTC, jhoward-lm commented on docs/architecture/0006-sbom-merge.md
> +# 6. 0006-sbom-merge.md
```suggestion
# 6. merge subcommand
```

2024-08-03 18:54 UTC, jhoward-lm commented
Just to document here for whoever ends up working on this, I think an implementation using a Go generic interface would be a clean way to do it.

<details>

<summary>Basic example</summary>

```go
package main

import (
	"fmt"

	"github.com/protobom/protobom/pkg/sbom"
)

type (
	Merger[T any] interface {
		Merge(*T) error
	}

	MergerBase[T any] struct {
		Base *T
		Merger[T]
	}
)

func (*MergerBase[T]) Merge(t *T) error {
	switch any(t).(type) {
	case *sbom.Metadata:
		fmt.Println("Merging metadata")
	case *sbom.Node:
		if _, ok := any(m.Base).(*sbom.Node); !ok {
			// return error
		}

		fmt.Println("Merging nodes")
	case *sbom.NodeList:
		fmt.Println("Merging node lists")
	case *sbom.Person:
		fmt.Println("Merging persons")
	case *sbom.Tool:
		fmt.Println("Merging tools")
	default:
		// return error
	}

	return nil
}

// Enforce implementation of interface at compile time
var _ Merger[sbom.Node] = (*MergerBase[sbom.Node])(nil)

func main() {
	merger := &MergerBase[sbom.Node]{}
	merger.Merge(&sbom.Node{})
}
```

</details>

[Go playground link](https://go.dev/play/p/-ApK7LFy0xv)

2024-10-23 14:41 UTC, ashearin approved these changes

2024-10-23 14:42 UTC, jhoward-lm approved these changes

2024-11-25 16:48 UTC, merged