Add keyless signing for all artifacts
bomctl/bomctl pull request #39
Opened 2024-04-24 02:50 UTC by idunbarh

This PR contains three changes:

- This PR adds keyless signing of checksum.txt, artifacts, and packages using cosign
- Instructions were added on how to verify signatures
- build artifacts from the goreleaser are saved for 3 days

Closes: #34

2024-04-24 17:38 UTC, jhoward-lm requested changes
Just one small suggestion in 3 places to leverage the `$certificate` and `$signature` variables in cosign args.

I don't have a strong preference about

`--output-signature=$signature`

versus

`--output-signature, $signature`

I do prefer to omit quotes in YAML documents wherever syntactically possible, so these suggested changes allow removal of the braces around the variable name, e.g. `"${signature}"` --> `$signature`

2024-04-24 17:38 UTC, jhoward-lm commented on .goreleaser.yml
> +    args: [sign-blob, --output-signature, "${artifact}-keyless.sig", --output-certificate, "${artifact}-keyless.pem", $artifact]
Will this work?

```suggestion
    args: [sign-blob, --output-signature=$signature, --output-certificate=$certificate, $artifact]
```

2024-04-24 17:38 UTC, jhoward-lm commented on .goreleaser.yml
> +    args: [sign-blob, --output-signature, "${artifact}-keyless.sig", --output-certificate, "${artifact}-keyless.pem", $artifact]
Will this work?

```suggestion
    args: [sign-blob, --output-signature=$signature, --output-certificate=$certificate, $artifact]
```

2024-04-24 17:38 UTC, jhoward-lm commented on .goreleaser.yml
> +    args: [sign-blob, --output-signature, "${artifact}-keyless.sig", --output-certificate, "${artifact}-keyless.pem", $artifact]
Will this work?

```suggestion
    args: [sign-blob, --output-signature=$signature, --output-certificate=$certificate, $artifact]
```

2024-04-24 17:45 UTC, jhoward-lm commented on .github/workflows/goreleaser.yml
> +          cosign-release: "v2.2.4" # optional
Mind removing the quotes and comment?

```suggestion
          cosign-release: v2.2.4
```

Unless this accepts SHA references;  if so, my suggestion would instead be:

```yaml
          cosign-release: fb651b4ddd8176bd81756fca2d988dd8611f514d # v2.2.4
```

2024-04-24 17:47 UTC, jhoward-lm commented
Also feel free to remove the `commitlint` workflow that checks the PR title. Since we're not using `svu` to generate the next release version and instead cutting releases via manual tag push now, it's a false positive

2024-04-24 19:03 UTC, jhoward-lm commented
> I was planning leaving the shell script that wraps `svu` incase we want to run it locally. Thoughts?

Works for me

2024-04-24 22:24 UTC, jhoward-lm commented on .goreleaser.yml
> +    args: [sign-blob, --output-signature, "${artifact}-keyless.sig", --output-certificate, "${artifact}-keyless.pem", $artifact]
Maybe theirs was originally written before goreleaser added support for that variable?

2024-04-24 22:24 UTC, jhoward-lm approved these changes

2024-04-25 14:12 UTC, ashearin approved these changes

2024-04-25 14:32 UTC, mfrystacky approved these changes
Had a question and a small fix

2024-04-25 14:32 UTC, mfrystacky commented on README.md
> +You can then verify this artifact with cosign the signature and the certificate.
You can then verify this artifact with cosign **using** the signature and the certificate.

2024-04-25 14:32 UTC, mfrystacky commented on README.md
> +Verified OK
Is this part of the command or the output?

2024-04-25 15:43 UTC, merged